[DEFAULT]

#
# From deepaas 
#

#
# Specify whether DEEPaaS should provide a train endpoint (default: True).
#  (boolean value)
train_endpoint = false

#
# Enable debug endpoint. If set we will provide all the information that you
# print to the standard output and error (i.e. stdout and stderr) through the
# "/debug" endpoint. Default is to not provide this information. This will not
# provide logging information about the API itself.
#  (boolean value)
debug_endpoint = false