# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    socib-beach-wracks-identification:
      container_testing_service: thisrepo-testing
      docker_build_options: '--no-cache'

sqa_criteria:
  qc_style:
    repos:
      socib-beach-wracks-identification:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      socib-beach-wracks-identification:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  qc_security:
    repos:
      socib-beach-wracks-identification:
        container: thisrepo-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  LANG: C.UTF-8
  JPL_DOCKERFORCEBUILD: "True"

timeout: 1200
